### PR TITLE
Walles/packaging

### PR DESCRIPTION
**Pull request by Shaywei**
Added basic setup.py

### CODE REVIEW

**Comment by nresare** [comment]
Looks like reasonable changes to me. Perhaps we should use the entry_points parameter to setuptools.setup instead of writing really short scripts in bin? Less boilerplate for FTW. (There is an example using this in gerrit2ghe setup.py)

**Comment by walles** [comment]
@nresare: Good point, fixed!

**Comment by nresare** [comment]
@walles the scripts arg to setup needs to go, as it references something that no longer exists. Also the main methods referenced are expected to take zero args.

**Comment by nresare** [comment]
looks good to me :) :+1:

**Pull request merged**
